// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyraekrihhiswbyianbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cmFla3JpaGhpc3dieWlhbmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTIxOTEsImV4cCI6MjA3MzAyODE5MX0.5ky3_-eFZJW6ehF4OcSB6R9TEI-WHuG9KcnlnLtSytg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});